### ISSUE TITLE
Using sonictool to extract genesis file from a sonic client

### ISSUE THREAD

**Issue by rpl-ffl** [Fantom-foundation/Norma#186]
`./sonictool --datadir <path-to-datadir> export genesis sonic.g` within a docker container during a Norma run results in the following panic:

```
panic: close of closed channel [recovered]
panic: close of closed channel

goroutine 1 [running]:
github.com/cockroachdb/pebble.Open.func1()     
    /client/vendor/github.com/cockroachdb/pebble/open.go:111 +0x153
panic({0x1550e20?, 0x19d6580?})
    /usr/local/go/src/runtime/panic.go:920 +0x270
github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).stopTicker(...)
    /client/vendor/github.com/cockroachdb/pebble/vfs/disk_health.go:95
github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).Close(0xc00023e180)
    /client/vendor/github.com/cockroachdb/pebble/vfs/disk_health.go:108 +0x25 
github.com/cockroachdb/pebble.Open.func2()        
    /client/vendor/github.com/cockroachdb/pebble/open.go:165 +0x48
github.com/cockroachdb/pebble.Open({0xc00009ee80, 0x19}, 0xc000196b00)
    /client/vendor/github.com/cockroachdb/pebble/open.go:207 +0xd56
github.com/Fantom-foundation/lachesis-base/kvdb/pebble.New({0xc00009ee80, 0x19},
0x488aad?, 0x64, 0x0, 0xc00012ee40)       
    /client/vendor/github.com/Fantom-foundation/lachesis-base/kvdb/pebble/pebble.go:141 +0x17e 
github.com/Fantom-foundation/lachesis-base/kvdb/pebble.
(*Producer).OpenDB(0xc00012ed98, {0xc00009edd3, 0x6}) 
    /client/vendor/github.com/Fantom-foundation/lachesis-base/kvdb/pebble/producer.go:55 +0x108
github.com/Fantom-foundation/go-opera/utils/dbutil/dbcounter.(*DBProducer).OpenDB(0xc00012edb0, {0xc00009edd3, 0x6}) 
    /client/utils/dbutil/dbcounter/dbcounter.go:94 +0x31
github.com/Fantom-foundation/lachesis-base/kvdb/flaggedproducer.(*Producer).OpenDB(0xc00023e080, {0xc00009edd3, 0x6})
    /client/vendor/github.com/Fantom-foundation/lachesis-base/kvdb/flaggedproducer/producer.go:35 +0xff 
github.com/Fantom-foundation/lachesis-base/kvdb/flaggedproducer.(*Producer).Initialize(0xc00023e080, {0xc00023e140, 0x4, 0x0?}, {0x0, 0x0, 0x0}) 
    /client/vendor/github.com/Fantom-foundation/lachesis-base/kvdb/flaggedproducer/producer.go:79 +0x105
github.com/Fantom-foundation/go-opera/integration.GetDbProducer({0xc00036f218?, 0x17595c3?}, {0x7?, 0x421d85?})
    /client/integration/db.go:48 +0x125
main.exportGenesis(0xc000126f20)
    /client/cmd/sonictool/export_genesis.go:36 +0x179
gopkg.in/urfave/cli%2ev1.HandleAction({0x14d1ce0?, 0x18647f8?}, 0x7?) 
    /client/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0x50
gopkg.in/urfave/cli%2ev1.Command.Run({{0x17594ff, 0x7}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x1786f9a, 0x28}, {0x0, ...}, ...}, ...) 
    /client/vendor/gopkg.in/urfave/cli.v1/command.go:210 +0x885
gopkg.in/urfave/cli%2ev1.(*App).RunAsSubcommand(0xc0004d3040, 0xc000126c60)
    /client/vendor/gopkg.in/urfave/cli.v1/app.go:379 +0xd07
gopkg.in/urfave/cli%2ev1.Command.startApp({{0x1758813, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x1762e48, 0x11}, {0x0, ...}, ...}, ...)
    /client/vendor/gopkg.in/urfave/cli.v1/command.go:298 +0xb18
gopkg.in/urfave/cli%2ev1.Command.Run({{0x1758813, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x1762e48, 0x11}, {0x0, ...}, ...}, ...)
    /client/vendor/gopkg.in/urfave/cli.v1/command.go:98 +0x3e5
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc000582340, {0xc000040080, 0x8, 0x8})
    /client/vendor/gopkg.in/urfave/cli.v1/app.go:255 +0xa67
main.main()
        /client/cmd/sonictool/main.go:387 +0x1455
```

**Comment by rpl-ffl** [comment]
Try waiting for the client to close before extract genesis:
`failed to make DB producer: failed to open existing databases: dirty state: lachesis: 0017D658DF5DA5F7CB, gossip: DE`
